name: Build and Deploy

on:
  push:
    branches:
    - main

env:
  # https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: m2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up maven settings
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "smartbear-repo", "url": "${{ secrets.NEXUS_URL }}", "snapshots": {"enabled": true} }]'
        servers: '[{ "id": "smartbear-repo", "username": "${{ secrets.NEXUS_USERNAME }}", "password": "${{ secrets.NEXUS_PASSWORD }}" }]'
    - name: Compile
      run: ./mvnw clean test-compile -B
    - name: Test and Deploy
      run: ./mvnw clean deploy -D pushChanges=false -D dependency-check.skip
